# Site settings
title: Weiqiang Zhou's homepage
email: kenzhou86@gmail.com
description: "This is Weiqiang Zhou's homepage"

author:
  name     : 'Weiqiang Zhou'
  email    : kenzhou86@gmail.com
  url      : http://weiqiangzhou.com/
  github   : https://github.com/WeiqiangZhou
  google   : https://scholar.google.com/citations?user=BDB3l1oAAAAJ&hl=en

github: https://github.com/WeiqiangZhou

paginate: 2
comments: true
paginate_path: "/page/:num"

sass:
  style: :compressed
  sass_dir: _sass

# Build settings
markdown  : kramdown
permalink : /:title/

