# Site settings
title: Weiqiang Zhou
email: kenzhou86@gmail.com
description: "welcome"

author:
  name     : 'Weiqiang Zhou'
  email    : kenzhou86@gmail.com
  url      : https://scholar.google.com/citations?user=BDB3l1oAAAAJ&hl=en

github: https://github.com/WeiqiangZhou



sass:
  style: :compressed
  sass_dir: _sass

# Build settings
markdown  : kramdown
permalink : /:title/
