# Site settings
title: Weiqiang Zhou
email: kenzhou86@gmail.com
description: 

 author:
  name     : 'Weiqiang Zhou'
  email    : kenzhou86@gmail.com
  
github: https://github.com/WeiqiangZhou


paginate: 
comments: true
paginate_path: "/page/:num"

sass:
  style: :compressed
  sass_dir: _sass

# Build settings
markdown  : kramdown
permalink : /:title/
