# Site settings
title: Weiqiang Zhou
email: kenzhou86@gmail.com
description: 
baseurl: ""
url: 

author:
  name     : 'Weiqiang Zhou'
  email    : kenzhou86@gmail@gmail.com
  url      : http://weiqiangzhou.com
  

github: https://github.com/WeiqiangZhou


paginate: 2
comments: true
paginate_path: "/page/:num"

sass:
  style: :compressed
  sass_dir: _sass

# Build settings
markdown  : kramdown
permalink : /:title/
