# Site settings
title: Weiqiang Zhou
email: kenzhou86@gmail.com
description: "welcome"


github: https://github.com/WeiqiangZhou



sass:
  style: :compressed
  sass_dir: _sass

# Build settings
markdown  : kramdown
permalink : /:title/
